const VOERINGEN=(window.DEOST_VOERINGEN||[]).filter(v=>v.actief!==false);
let state={search:'',kleur:'alle',materiaal:'alle',uitstraling:'alle'};
function uniq(values){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'nl'))}
function options(id,label,values){const el=document.getElementById(id);el.innerHTML=`<option value="alle">Alle ${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function init(){options('kleur','kleuren',uniq(VOERINGEN.map(v=>v.kleur)));options('materiaal','materialen',uniq(VOERINGEN.map(v=>v.materiaal)));options('uitstraling','uitstralingen',uniq(VOERINGEN.flatMap(v=>v.uitstraling||[])));render()}
function match(v){const q=state.search.trim().toLowerCase();if(q&&!([v.id,v.naam,v.kleur,v.materiaal,...(v.uitstraling||[]),...(v.klantLabels||[])].join(' ').toLowerCase().includes(q)))return false;if(state.kleur!=='alle'&&v.kleur!==state.kleur)return false;if(state.materiaal!=='alle'&&v.materiaal!==state.materiaal)return false;if(state.uitstraling!=='alle'&&!(v.uitstraling||[]).includes(state.uitstraling))return false;return true}
function card(v){const img=v.swatch||v.closeup||'';return `<article class="card"><div class="img">${img?`<img src="${esc(img)}" alt="${esc(v.naam)}" onerror="this.style.display='none'">`:''}<div class="actions"><button class="icon" onclick="openZoom('${esc(v.id)}')"><i class="ti ti-zoom-in"></i></button><button class="icon" onclick="openInfo('${esc(v.id)}')"><i class="ti ti-info-circle"></i></button></div></div><div class="content"><div class="name">${esc(v.naam)}</div><div class="meta">${esc(v.materiaal||'')} · ${esc(v.kleur||'')}<br>${esc((v.uitstraling||[]).join(' · '))}</div><div class="tags">${(v.klantLabels||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div class="buttons"><button class="btn secondary" onclick="openInfo('${esc(v.id)}')">Details</button></div></article>`}
function render(){const list=VOERINGEN.filter(match);document.getElementById('count').textContent=`${list.length} resultaat${list.length===1?'':'en'}`;document.getElementById('grid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Geen voeringen gevonden. Wis een filter.</div>'}
function resetFilters(){state={search:'',kleur:'alle',materiaal:'alle',uitstraling:'alle'};document.getElementById('search').value='';['kleur','materiaal','uitstraling'].forEach(id=>document.getElementById(id).value='alle');render()}
function get(id){return VOERINGEN.find(v=>v.id===id)}
function openZoom(id){const v=get(id);if(!v)return;document.getElementById('media').innerHTML=`<img src="${esc(v.closeup||v.swatch||'')}" alt="${esc(v.naam)}">`;document.getElementById('content').innerHTML=`<div class="modal-title">${esc(v.naam)}</div><div class="text">${esc(v.materiaal||'')} · ${esc(v.kleur||'')}</div>`;document.getElementById('modal').style.display='flex'}
function openInfo(id){const v=get(id);if(!v)return;document.getElementById('media').innerHTML=v.video?`<video autoplay muted loop playsinline><source src="${esc(v.video)}" type="video/mp4"></video>`:`<img src="${esc(v.closeup||v.swatch||'')}" alt="${esc(v.naam)}">`;document.getElementById('content').innerHTML=`<div class="modal-title">${esc(v.naam)}</div><div class="text">${esc(v.materiaal||'')} · ${esc(v.kleur||'')}</div>${v.korteUitleg?`<div class="section-title">Uitleg</div><div class="text">${esc(v.korteUitleg)}</div>`:''}${v.advies?`<div class="section-title">Advies</div><div class="text">${esc(v.advies)}</div>`:''}`;document.getElementById('modal').style.display='flex'}
function closeModal(){document.getElementById('modal').style.display='none'}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});init();
