/* De Oost — stoffen.js
   Live stofbibliotheek voor de configurator.
   Plaats dit bestand naast deoost_stijlconfigurator.html in /configurator/.
   Beelden staan relatief vanaf /configurator/, bijvoorbeeld:
   stoffen/holland-sherry-crispaire/310012_swatch.jpg
*/

window.DEOST_STOFFEN = [

  {
    id: "MOCK-NAVY-HOPSACK",
    leverancier: "De Oost Mock Library",
    bunch: "Demo Suiting",
    stofnummer: "MOCK-001",
    naam: "Mock donkerblauw hopsack",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "hopsack",
    patroon: "effen",
    kleur: "navy",
    patroonkleur: "",
    gewicht: "280g",
    prijsGroep: "B",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["zakelijk", "bruiloft", "casual", "zomer"],
    seizoen: ["lente", "zomer", "herfst"],
    formaliteit: ["semi-formeel"],
    uitstraling: ["klassiek", "rustig", "veelzijdig"],
    klantLabels: ["Mock", "Veelzijdig", "Structuur"],
    korteUitleg: "Demo-stof om de bibliotheek, filters en selectiekaart te testen.",
    advies: "Gebruik deze mock-stof om te zien hoe een vorige-order stof en de stofkaart verschijnen.",
    minderGeschiktVoor: "Niet gebruiken als echte catalogusstof.",
    swatch: "stoffen/mock/mock_navy_hopsack_swatch.svg",
    closeup: "stoffen/mock/mock_navy_hopsack_closeup.svg",
    video: "",
    seoUrl: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "MOCK-GREY-FLANNEL",
    leverancier: "De Oost Mock Library",
    bunch: "Demo Flannel",
    stofnummer: "MOCK-002",
    naam: "Mock middengrijs flanel",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "flanel",
    patroon: "effen",
    kleur: "grijs",
    patroonkleur: "",
    gewicht: "340g",
    prijsGroep: "C",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["zakelijk", "winter", "casual"],
    seizoen: ["herfst", "winter"],
    formaliteit: ["semi-formeel"],
    uitstraling: ["zacht", "klassiek", "rustig"],
    klantLabels: ["Mock", "Flanel", "Winter"],
    korteUitleg: "Een zachte demo-flanel met rustige grijze uitstraling.",
    advies: "Mooi als broekstof of als klassiek winterpak in de demo.",
    minderGeschiktVoor: "Minder geschikt voor warme zomerdagen.",
    swatch: "stoffen/mock/mock_grey_flannel_swatch.svg",
    closeup: "stoffen/mock/mock_grey_flannel_swatch.svg",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "MOCK-POW-BLUE",
    leverancier: "De Oost Mock Library",
    bunch: "Demo Checks",
    stofnummer: "MOCK-003",
    naam: "Mock Prince of Wales met blauwe overruit",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "twill",
    patroon: "prince_of_wales",
    kleur: "grijs",
    patroonkleur: "blauw",
    gewicht: "300g",
    prijsGroep: "C",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["bruiloft", "zakelijk"],
    seizoen: ["lente", "herfst", "winter"],
    formaliteit: ["semi-formeel"],
    uitstraling: ["opvallend", "klassiek"],
    klantLabels: ["Mock", "Ruit", "Bruiloft"],
    korteUitleg: "Demo-ruit om patroonfilters en zoekfunctie te testen.",
    advies: "Goed zichtbaar voorbeeld voor klanten die door patronen willen bladeren.",
    minderGeschiktVoor: "Minder rustig dan effen navy of grijs.",
    swatch: "stoffen/mock/mock_pow_swatch.svg",
    closeup: "stoffen/mock/mock_pow_swatch.svg",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "MOCK-BLACK-BARATHEA",
    leverancier: "De Oost Mock Library",
    bunch: "Demo Evening",
    stofnummer: "MOCK-004",
    naam: "Mock zwarte barathea",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "barathea",
    patroon: "effen",
    kleur: "zwart",
    patroonkleur: "",
    gewicht: "320g",
    prijsGroep: "D",
    geschiktVoor: ["black_tie"],
    gebruik: ["avond", "gala", "bruiloft"],
    seizoen: ["herfst", "winter", "lente"],
    formaliteit: ["formeel"],
    uitstraling: ["formeel", "klassiek", "rustig"],
    klantLabels: ["Mock", "Black Tie", "Barathea"],
    korteUitleg: "Demo-avondstof voor smoking en black-tie onderdelen.",
    advies: "Gebruik deze stof om de black-tie route en avondafwerking te testen.",
    minderGeschiktVoor: "Niet bedoeld als casual stof.",
    swatch: "stoffen/mock/mock_black_barathea_swatch.svg",
    closeup: "stoffen/mock/mock_black_barathea_swatch.svg",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "MOCK-BURGUNDY-VELVET",
    leverancier: "De Oost Mock Library",
    bunch: "Demo Velvet",
    stofnummer: "MOCK-005",
    naam: "Mock bordeaux velvet",
    materiaal: ["katoen"],
    samenstelling: "100% katoen",
    weving: "velvet",
    patroon: "effen",
    kleur: "bordeaux",
    patroonkleur: "",
    gewicht: "350g",
    prijsGroep: "D",
    geschiktVoor: ["black_tie", "tenue_de_ville"],
    gebruik: ["avond", "gala", "bruiloft"],
    seizoen: ["herfst", "winter"],
    formaliteit: ["semi-formeel", "feestelijk"],
    uitstraling: ["opvallend", "rijk", "feestelijk"],
    klantLabels: ["Mock", "Velvet", "Statement"],
    korteUitleg: "Demo-velvet voor avondjasjes en opvallende keuzes.",
    advies: "Mooi om de visuele bibliotheek met rijkere texturen te testen.",
    minderGeschiktVoor: "Niet bedoeld voor een ingetogen business suit.",
    swatch: "stoffen/mock/mock_burgundy_velvet_swatch.svg",
    closeup: "stoffen/mock/mock_burgundy_velvet_swatch.svg",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "MOCK-NATURAL-LINEN",
    leverancier: "De Oost Mock Library",
    bunch: "Demo Summer",
    stofnummer: "MOCK-006",
    naam: "Mock naturel linnen",
    materiaal: ["linnen"],
    samenstelling: "100% linnen",
    weving: "plain",
    patroon: "effen",
    kleur: "beige",
    patroonkleur: "",
    gewicht: "240g",
    prijsGroep: "B",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["zomer", "bruiloft", "casual"],
    seizoen: ["zomer", "lente"],
    formaliteit: ["informeel", "semi-formeel"],
    uitstraling: ["zacht", "casual", "licht"],
    klantLabels: ["Mock", "Linnen", "Zomer"],
    korteUitleg: "Demo-linnen voor lichte zomerpakken en losse jasjes.",
    advies: "Handig voor het testen van kleur- en materiaalfilters.",
    minderGeschiktVoor: "Minder geschikt voor zeer formele avondkleding.",
    swatch: "stoffen/mock/mock_linen_swatch.svg",
    closeup: "stoffen/mock/mock_linen_swatch.svg",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },

  {
    id: "HS-CRISPAIRE-310012",
    leverancier: "Holland & Sherry",
    bunch: "Crispaire",
    stofnummer: "310012",
    naam: "Navy Crispaire",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "plain",
    patroon: "effen",
    kleur: "navy",
    patroonkleur: "",
    gewicht: "310g",
    prijsGroep: "C",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["zakelijk", "bruiloft", "reis", "zomer"],
    seizoen: ["lente", "zomer", "herfst"],
    formaliteit: ["formeel", "semi-formeel"],
    uitstraling: ["klassiek", "rustig", "veelzijdig"],
    klantLabels: ["Kreukarm", "Ademend", "Veelzijdig"],
    korteUitleg: "Een klassieke reis- en zomerwol met een droge touch en rustige uitstraling.",
    advies: "Sterk als veelzijdig navy pak voor zakelijk gebruik, reizen en bruiloften.",
    minderGeschiktVoor: "Minder uitgesproken dan flanel, velvet of duidelijke ruiten.",
    swatch: "stoffen/holland-sherry-crispaire/310012_swatch.jpg",
    closeup: "stoffen/holland-sherry-crispaire/310012_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "HS-NAVY-HOPSACK",
    leverancier: "Holland & Sherry",
    bunch: "Voorbeeld bunch",
    stofnummer: "HS-2341",
    naam: "Donkerblauw hopsack",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "hopsack",
    patroon: "effen",
    kleur: "navy",
    patroonkleur: "",
    gewicht: "280g",
    prijsGroep: "B",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["zakelijk", "bruiloft", "casual"],
    seizoen: ["lente", "zomer", "herfst"],
    formaliteit: ["semi-formeel"],
    uitstraling: ["klassiek", "rustig", "veelzijdig"],
    klantLabels: ["Veelzijdig", "Ademend", "Structuur"],
    korteUitleg: "Een open geweven wol met duidelijke structuur. Minder glad dan een klassieke kamgarenstof.",
    advies: "Kies deze stof voor een donkerblauw pak dat minder formeel en minder vlak oogt dan een gladde business suit.",
    minderGeschiktVoor: "Minder geschikt voor de meest formele avondkleding.",
    swatch: "stoffen/holland-sherry-voorbeeld/HS-NAVY-HOPSACK_swatch.jpg",
    closeup: "stoffen/holland-sherry-voorbeeld/HS-NAVY-HOPSACK_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "https://www.youtube.com/",
    actief: true
  },
  {
    id: "FB-GREY-FLANNEL",
    leverancier: "Fox Brothers",
    bunch: "Classic Flannel",
    stofnummer: "FB-0802",
    naam: "Middengrijs flanel",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "flanel",
    patroon: "effen",
    kleur: "grijs",
    patroonkleur: "",
    gewicht: "340g",
    prijsGroep: "C",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["zakelijk", "winter", "bruiloft"],
    seizoen: ["herfst", "winter"],
    formaliteit: ["semi-formeel", "formeel"],
    uitstraling: ["klassiek", "zacht", "formeel"],
    klantLabels: ["Winter", "Zacht", "Klassiek"],
    korteUitleg: "Flanel heeft een zachte, matte uitstraling en voelt warmer en voller dan een gladde worsted.",
    advies: "Een sterke keuze voor een klassiek winterpak of tenue de ville met rijker karakter.",
    minderGeschiktVoor: "Minder geschikt voor warm weer of zeer intensief zomers gebruik.",
    swatch: "stoffen/fox-brothers-classic-flannel/FB-GREY-FLANNEL_swatch.jpg",
    closeup: "stoffen/fox-brothers-classic-flannel/FB-GREY-FLANNEL_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "CC-POW-BLUE",
    leverancier: "Caccioppoli",
    bunch: "Voorbeeld bunch",
    stofnummer: "CC-POW-01",
    naam: "Blauw Prince of Wales",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "twill",
    patroon: "prince_of_wales",
    kleur: "blauw",
    patroonkleur: "lichtblauw",
    gewicht: "280g",
    prijsGroep: "C",
    geschiktVoor: ["pak_kostuum", "tenue_de_ville"],
    gebruik: ["bruiloft", "zakelijk", "casual"],
    seizoen: ["lente", "herfst"],
    formaliteit: ["semi-formeel"],
    uitstraling: ["klassiek", "opvallend", "rijk"],
    klantLabels: ["Patroon", "Bruiloft", "Karakter"],
    korteUitleg: "Prince of Wales, ook Glencheck genoemd, is een klassiek ruitpatroon met meer diepte dan een effen stof.",
    advies: "Geschikt als u een pak wilt met karakter, zonder dat het meteen luid of modegevoelig wordt.",
    minderGeschiktVoor: "Minder ingetogen dan effen navy of grijs.",
    swatch: "stoffen/caccioppoli-voorbeeld/CC-POW-BLUE_swatch.jpg",
    closeup: "stoffen/caccioppoli-voorbeeld/CC-POW-BLUE_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "https://www.youtube.com/",
    actief: true
  },
  {
    id: "LN-NATURAL-LINEN",
    leverancier: "De Oost",
    bunch: "Linnen selectie",
    stofnummer: "LN-3302",
    naam: "Naturel linnen",
    materiaal: ["linnen"],
    samenstelling: "100% linnen",
    weving: "plain",
    patroon: "effen",
    kleur: "beige",
    patroonkleur: "",
    gewicht: "260g",
    prijsGroep: "B",
    geschiktVoor: ["tenue_de_ville"],
    gebruik: ["zomer", "bruiloft", "casual"],
    seizoen: ["zomer"],
    formaliteit: ["informeel", "semi-formeel"],
    uitstraling: ["zacht", "informeel", "licht"],
    klantLabels: ["Zomer", "Luchtig", "Informeel"],
    korteUitleg: "Linnen is luchtig, natuurlijk en levendig. Kreuk hoort bij het karakter van de stof.",
    advies: "Mooi voor zomerbruiloften, losse jasjes en ontspannen tenue de ville combinaties.",
    minderGeschiktVoor: "Minder geschikt wanneer u een strak, kreukarm of zeer formeel beeld zoekt.",
    swatch: "stoffen/de-oost-linnen/LN-NATURAL-LINEN_swatch.jpg",
    closeup: "stoffen/de-oost-linnen/LN-NATURAL-LINEN_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "",
    actief: true
  },
  {
    id: "BT-BLACK-BARATHEA",
    leverancier: "Bateman Ogden",
    bunch: "Eveningwear",
    stofnummer: "BT-001",
    naam: "Zwart barathea",
    materiaal: ["wol"],
    samenstelling: "100% wol",
    weving: "barathea",
    patroon: "effen",
    kleur: "zwart",
    patroonkleur: "",
    gewicht: "320g",
    prijsGroep: "C",
    geschiktVoor: ["black_tie"],
    gebruik: ["avond", "gala", "black_tie"],
    seizoen: ["alle_seizoenen"],
    formaliteit: ["formeel"],
    uitstraling: ["formeel", "klassiek", "rustig"],
    klantLabels: ["Black tie", "Formeel", "Avond"],
    korteUitleg: "Barathea is een klassieke avondstof met subtiele structuur en diepe, formele uitstraling.",
    advies: "Een logische keuze voor smoking en galakleding.",
    minderGeschiktVoor: "Niet bedoeld als dagelijks pak of casual tailoring.",
    swatch: "stoffen/bateman-ogden-eveningwear/BT-BLACK-BARATHEA_swatch.jpg",
    closeup: "stoffen/bateman-ogden-eveningwear/BT-BLACK-BARATHEA_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "https://www.youtube.com/",
    actief: true
  },
  {
    id: "VL-BORDEAUX-VELVET",
    leverancier: "De Oost",
    bunch: "Velvet selectie",
    stofnummer: "VL-7703",
    naam: "Bordeaux velvet",
    materiaal: ["katoen"],
    samenstelling: "100% katoen velvet",
    weving: "velvet",
    patroon: "effen",
    kleur: "bordeaux",
    patroonkleur: "",
    gewicht: "350g",
    prijsGroep: "D",
    geschiktVoor: ["black_tie", "tenue_de_ville"],
    gebruik: ["avond", "gala", "bruiloft"],
    seizoen: ["herfst", "winter"],
    formaliteit: ["semi-formeel", "feestelijk"],
    uitstraling: ["opvallend", "rijk", "feestelijk"],
    klantLabels: ["Velvet", "Avond", "Statement"],
    korteUitleg: "Velvet geeft een diepe kleur en sterke lichtwerking. Ideaal voor smoking jackets en avondstukken.",
    advies: "Mooi wanneer het kledingstuk een uitgesproken, feestelijk karakter mag hebben.",
    minderGeschiktVoor: "Minder geschikt als u iets zeer ingetogens zoekt.",
    swatch: "stoffen/de-oost-velvet/VL-BORDEAUX-VELVET_swatch.jpg",
    closeup: "stoffen/de-oost-velvet/VL-BORDEAUX-VELVET_closeup.jpg",
    video: "",
    blogUrl: "https://www.deoost.nl/blog",
    videoUrl: "https://www.youtube.com/",
    actief: true
  }
];
